FROM debian

ADD debian.list /etc/apt/sources.list.d/

RUN apt-get update && apt-get -y upgrade && apt -y install nginx && apt-get clean && \
    cd /var/www/ && rm -rf ./* && \
    mkdir -p dota2.com/img && \
    chmod -R 754 /var/www/dota2.com/ && \
    useradd Evgeniy && groupadd Malyshev && usermod -a -G Malyshev Evgeniy && \
    chown -R Evgeniy:Malyshev /var/www/dota2.com && \
    sed -i 's$/var/www/html$/var/www/dota2.com$g' /etc/nginx/sites-enabled/default && \
    sed -i 's/user www-data/user Evgeniy/g' /etc/nginx/nginx.conf
	
ADD index.html /var/www/dota2.com/
ADD img.jpg /var/www/dota2.com/img/
CMD ["nginx", "-g", "daemon off;"]